import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LOCALES = ["en", "no"] as const;
export function generateStaticParams() {
  return LOCALES.map((lng) => ({ lng }));
}

export default function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
